name: Java Native Build - Linux
# This workflow will build a java project and produce a GraalVM native image

on:
  workflow_dispatch:
    inputs:
      build_env:
        required: true
        default: "ubuntu-latest"
        type: choice
        options: ['ubuntu-latest', 'macos-latest', 'windows-latest', 'ubuntu-20.04', 'macos-11', 'windows-2019']
        description: "Use to select OS to build native image for."

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Build
        run: mvn --no-transfer-progress clean compile

      - name: Unit Test
        run: mvn --no-transfer-progress test

  build_native:
    if: success()
    needs: [ build_and_test ]
    name: Build native on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [${{ github.event.inputs.deploy_environment }}]
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'

      - name: Version Details
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Native Build ${{ matrix.os }}
        run: |
          mvn --no-transfer-progress -Pnative -DskipTests package -X
          mv target/scanoss-java-* target/scanoss-java-${{ matrix.os }}

      - name: List Packages
        continue-on-error: true
        run: |
          ls -la target/

      - name: Test Binary
        run: |
          ./target/scanoss-java-${{ matrix.os }} -h
          ./target/scanoss-java-${{ matrix.os }} wfp src > fingers-${{ matrix.os }}.wfp
